# Archivo de configuración para Netlify

# Regla para el proxy de la API. Esta debe ir PRIMERO.
[[redirects]]
  from = "/api/*"
  to = "https://rovalverde.alwaysdata.net/:splat"
  status = 200

# Regla para Aplicaciones de Página Única (SPA). Esta debe ir AL FINAL.
# Redirige todas las demás peticiones al index.html para que React Router funcione.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200